# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        RecordStoreBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_EDITOR]
        ROLE_EDITOR: [ROLE_USER]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_provider:
            entity:
                class: RecordStoreBundle:User


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~
            pattern: ^/
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                provider: user_provider
                login_path: user_login
                check_path: user_login
            logout:
                path: user_logout

    access_control:
        - { path: ^/product/products , roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/product/new , roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: /edit , roles: [ROLE_ADMIN, ROLE_EDITOR, ROLE_USER] }
        - { path: ^/product/id , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login , roles: IS_AUTHENTICATED_ANONYMOUSLY }

