# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.image_uploader:
        class:     RecordStoreBundle\Services\UploadService
        arguments: ['%root_dir%']
    repo.promotions:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - \RecordStoreBundle\Entity\Promotion
    promotion_manager:
        class:     RecordStoreBundle\Services\PromotionManager
        arguments: ['@repo.promotions']
    price_calculator:
        class:     RecordStoreBundle\Services\PriceCalculator
        arguments: ['@promotion_manager']